//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FayzullinaElvina_ExamLavka.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterService
    {
        public int Id { get; set; }
        public Nullable<int> IdMaster { get; set; }
        public Nullable<int> IdService { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
