//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FayzullinaElvina_ExamLavka.DBConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FayzullinaElvina_LavkaExamEntities1 : DbContext
    {
        public FayzullinaElvina_LavkaExamEntities1()
            : base("name=FayzullinaElvina_LavkaExamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionService> CollectionService { get; set; }
        public virtual DbSet<MasterQualification> MasterQualification { get; set; }
        public virtual DbSet<MasterService> MasterService { get; set; }
        public virtual DbSet<Records> Records { get; set; }
        public virtual DbSet<RequestForPromotion> RequestForPromotion { get; set; }
        public virtual DbSet<ReviewsAboutMasters> ReviewsAboutMasters { get; set; }
        public virtual DbSet<ReviewsAboutServices> ReviewsAboutServices { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<StatusRequest> StatusRequest { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeService> TypeService { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersCards> UsersCards { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
