//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FayzullinaElvina_ExamLavka.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForPromotion
    {
        public int Id { get; set; }
        public Nullable<int> IdMaster { get; set; }
        public string Request { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual StatusRequest StatusRequest { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
