//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FayzullinaElvina_ExamLavka.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewsAboutMasters
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdMaster { get; set; }
        public string Review { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
